Rename Feed to Subject
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #114
Opened 2023-10-18 15:47 UTC by SteveLasker

PR addressing the conversation around Feed is redundant with Subject, as defined in CWT
- [3.1.2.  sub (Subject) Claim](https://www.rfc-editor.org/rfc/rfc8392.html#section-3.1.2)
    >    The "sub" (subject) claim has the same meaning and processing rules
    >    as the "sub" claim defined in Section 4.1.2 of [RFC7519], except that
    >    the value is a StringOrURI, as defined in Section 2 of this
    >    specification.  The Claim Key 2 is used to identify this claim.
- [4.1.2.  "sub" (Subject) Claim](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.2)
    >    The "sub" (subject) claim identifies the principal that is the
    >    subject of the JWT.  The claims in a JWT are normally statements
    >    about the subject.  The subject value MUST either be scoped to be
    >    locally unique in the context of the issuer or be globally unique.
    >    The processing of this claim is generally application specific.  The
    >    "sub" value is a case-sensitive string containing a StringOrURI
    >    value.  Use of this claim is OPTIONAL.

This PR intentionally contrasts #108

Choice for folks to vote upon:

- [ ] Rename Feed to Subject
- [ ] Should we also include CWT_Claims, which contains the subject #108

2023-10-18 16:03 UTC, OR13 approved these changes

2023-10-18 16:08 UTC, JAG-UK requested changes
One small but important nit

2023-10-18 16:08 UTC, JAG-UK commented on draft-ietf-scitt-architecture.md
> +- Subject (label: `2`): The Subject to which the Statement belongs, as a string, chosen by the Issuer.
...to which the statement _refers_, surely?

2023-10-18 16:27 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +  2 => tstr              ; Subject
I didn't make that explicit change, but yes an issuer of a signed statement must have a subject.

2023-10-18 16:30 UTC, yogeshbdeshpande approved these changes
LGTM!

2023-10-19 21:28 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +  2 => tstr              ; Subject
Isn't 2 'crit`? Shouldn't be nested in a 13 (see https://www.ietf.org/archive/id/draft-ietf-cose-cwt-claims-in-headers-06.html#name-representation)?

2023-10-19 22:36 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +  2 => tstr              ; Subject
Ahh, yes, I incorrectly pulled `2` from the CWT spec. 
In this PR, we're not pulling in CWT. That is deferred to #108
This PR renames `Feed` to `Subject`, aligning with the definition of Subject, within CWT. 
Can we agree with this incremental step? If so, what tag should we use? I can repurpose 392, but I think we agree [cbor-tags](https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml) should have a common tag  for `subject`, which is outside the scope of this PR.

- Do we agree with the rename?
- What CBOR tag should we use?

2023-10-20 14:20 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +  2 => tstr              ; Subject
To unblock, I've set the label to 392 (previous temporary label), as a `bytestring`, similar to #111. This unblocks the rename, with the ability to relax to `string` if we decide, or possibly shift to a CWT (#108).

2023-10-20 14:22 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +  2 => tstr              ; Subject
Above reference is outdated. Please see updated [line 658](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/114/files#diff-585fb424519b79cf000445f3425fa56d328cbaca5d2a622740ddc4e5ca91dbe1R658)
> `392 => bstr            ; Subject`

2023-10-20 18:02 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +  2 => tstr              ; Subject
With #108 merged, removing this entry.

2023-10-20 18:06 UTC, merged