Some Header Re-Shuffeling
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #140
Opened 2023-12-07 08:31 UTC by henkbirkholz

simplified a few references & added a WG, some reordering

2023-12-07 09:33 UTC, yogeshbdeshpande approved these changes
LGTM!

2023-12-07 14:56 UTC, aj-stein-nist requested changes
A small fix and then it will be ready to 🚢 it.

2023-12-07 14:56 UTC, aj-stein-nist commented on draft-ietf-scitt-architecture.md
> +  I-D.ietf-cose-cwt-claims-in-headers: CWT-CLAIMS-COSE
Per the [`kramdown-rfc` docs]() and local testing, you need to flip the key and value.

```suggestion
  COSWID: RFC9393
  CWT_CLAIMS_COSE: I-D.ietf-cose-cwt-claims-in-headers
```

Tested this locally in the same container as GHA by using this branch, running `make clean`, then `make. This suggestion will remove [the relevant build failures](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/actions/runs/7125650198/job/19401978042#step:6:35) and allow it to publish once reviewed and merged by others.

2023-12-12 03:53 UTC, SteveLasker commented
> A small fix and then it will be ready to 🚢 it.

Thanks, @aj-stein-nist

2023-12-12 03:53 UTC, SteveLasker approved these changes
LGTM

2023-12-12 03:53 UTC, merged