Clarify Feed and Subject
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #165
Opened 2024-01-18 22:30 UTC by SteveLasker

Explains Feed as the logical collection, with `CWT_Claims sub` (Subject) as the property to represent the collection.

2024-01-19 14:13 UTC, fournet requested changes
For simplicity, I would prefer to keep only one of the two in the Terminology.

2024-01-19 14:14 UTC, henkbirkholz commented
> For simplicity, I would prefer to keep only one of the two in the Terminology.

That seems pretty reasonable to me. Are there any reasons to keep both?

2024-01-19 22:16 UTC, SteveLasker commented
> > For simplicity, I would prefer to keep only one of the two in the Terminology.
> 
> That seems pretty reasonable to me. Are there any reasons to keep both?

While I'd agree less is more, this keeps coming back when we try to explain it.

- A feed is a known concept for a collection of related data
- We're using CWT_Claims `sub`, which also makes sense to align with existing specs
- We avoided Artifact ID

Attempting to describe a collection of statements as a subject doesn't resonate.

We can keep Feed as the concept, and simply say CWT_Claims `sub` is how you set an identifier for the feed.
How does that work?

2024-01-30 13:45 UTC, henkbirkholz commented
Then we should deprecate the term feed in discussions, too, and just explain how a subject is used as a subject in this context?

2024-01-30 13:46 UTC, henkbirkholz requested changes
Feed stills seems to be a superfluous term.

2024-01-30 15:25 UTC, OR13 requested changes
I will revise my suggestion to something that is mergable

2024-01-30 15:31 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +Issuers use `CWT_Claims:sub` (Subject)  to create a coherent sequence of Signed Statements about the same Artifact and Verifiers use the Feed to ensure completeness and Non-equivocation in supply cha
```suggestion
: An unordered collection of arbitrary data (artifacts, signed statements, receipts, or other data) related to the text identifiers, observed by the transparency service in the subject field of the CWT claim property of the protected header of Signed Statements.
```

2024-01-30 15:33 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +Subject is a property of the dedicated, protected header attribute `15: CWT_Claims` within the protected header of the COSE envelope, to correlate the Statements.
```suggestion
: This term has the same definition as in RFC8392.
```

2024-01-31 04:44 UTC, SteveLasker commented
Updated to merge in PR feedback

2024-01-31 21:06 UTC, SteveLasker commented
@henkbirkholz, @OR13, @fournet, PTAL as I've made some updates.

2024-02-01 19:19 UTC, merged