Auditor is an example of a Relying Party.
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #255
Opened 2024-07-20 16:33 UTC by hannestschofenig

2024-07-20 22:09 UTC, aj-stein-nist approved these changes

2024-07-21 16:30 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +: an entity that checks the correctness and consistency of all Transparent Statements issued by a Transparency Service. An Auditor is an example of a Relying Party.
```suggestion
: an entity that checks the correctness and consistency of all Transparent Statements issued by a Transparency Service.
An Auditor is an example of a Relying Party.
```

2024-07-21 16:38 UTC, rjb4standards commented
@SteveLasker I'm concerned that this "overloading" of Auditor semantics is going to create ambiguities and confusion.
I continue to believe we need to define two distinctive roles; A Gatekeeper that ensures only verified "signed statements" following registration policies are placed into the registry and a "Relying Party" that "trusts" the information contained in a Registry.
IMO, an auditor is the "checker" making sure that policies are being followed, which adds integrity to the Registry processes and procedures and the Registry operator (Transparency Service) is properly following the SCITT protocol and registration policy processes and procedures.

2024-07-21 16:49 UTC, roywill commented
I am fine with this change.  The larger issue that Steve points out I believe can be left out.

2024-07-21 18:12 UTC, SteveLasker approved these changes
LGTM

2024-07-21 21:15 UTC, roywill approved these changes

2024-07-21 21:17 UTC, OR13 approved these changes

2024-07-21 21:41 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +An Auditor is an example of a Relying Party.
```suggestion
An Auditor is an example of a specialized Relying Party.
```

2024-07-21 21:42 UTC, henkbirkholz requested changes
not only an example, but also literally a specialization (narrower term)

2024-07-21 23:05 UTC, henkbirkholz approved these changes

2024-07-21 23:06 UTC, merged