Replacing Verifier with Relying Party
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #257
Opened 2024-07-20 17:07 UTC by hannestschofenig

2024-07-20 22:10 UTC, aj-stein-nist approved these changes

2024-07-21 00:22 UTC, JAG-UK approved these changes

2024-07-21 17:17 UTC, roywill requested changes
Slight text change suggested.

2024-07-21 18:04 UTC, hannestschofenig commented on draft-ietf-scitt-architecture.md
> +Issuers can register their Signed Statements on any Transparency Service, with the guarantee that all Relying Parties will be able to verify them.
done

2024-07-21 18:11 UTC, SteveLasker approved these changes
LGTM

2024-07-21 21:34 UTC, OR13 approved these changes

2024-07-21 21:36 UTC, OR13 approved these changes

2024-07-21 21:49 UTC, henkbirkholz approved these changes

2024-07-21 23:09 UTC, merged