Added "Verifiable Data Structure" Term
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #258
Opened 2024-07-20 17:11 UTC by hannestschofenig

2024-07-20 22:22 UTC, aj-stein-nist approved these changes

2024-07-21 00:23 UTC, JAG-UK approved these changes

2024-07-21 17:30 UTC, roywill requested changes
The usage of Verifiable Data Structure down below points at a definition from another RFC.  We should import that instead of redefining.

2024-07-21 18:07 UTC, hannestschofenig commented
Added reference to {{I-D.ietf-cose-merkle-tree-proofs}}.

2024-07-21 21:16 UTC, roywill approved these changes

2024-07-21 21:17 UTC, OR13 approved these changes

2024-07-21 21:34 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +: a data structure which supports one or proof types, such as "inclusion proofs" or "consistency proofs" (as defined in {{-COMETRE}}).
```suggestion
: a data structure which supports one or more proof types, such as "inclusion proofs" or "consistency proofs" (as defined in {{-COMETRE}}).
```

2024-07-21 23:09 UTC, merged