Removed mentioning of "Identity Document"
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #259
Opened 2024-07-20 17:15 UTC by hannestschofenig

Reason: Term was used only twice, not defined, and does not seem to play an important role.

2024-07-20 22:42 UTC, aj-stein-nist approved these changes

2024-07-21 17:36 UTC, roywill requested changes
I am fine with removing Identity Documents but replacing it with Credentials Trust Anchors is not correct.  A credential reference is what the "signer" supplies and the system builds the chain in the context of CA issued X.509.

2024-07-21 17:54 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> + | Statement |           '----+--+------'
```suggestion
 '-----+----'            .-------------.
       v                |  Credentials  |
  .----+----.           | Trust Anchors |
 | Statement |           '----+--+-----'
```

2024-07-21 21:17 UTC, roywill approved these changes

2024-07-21 21:33 UTC, OR13 approved these changes
yolo

2024-07-21 21:37 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +At least one identifier to a credential MUST be included in the protected header of the COSE Envelope, as one of `x5t` or `kid`.
```suggestion
At least one identifier representing one credential MUST be included in the protected header of the COSE Envelope, as one of `x5t` or `kid`.
```

2024-07-21 21:38 UTC, henkbirkholz approved these changes
fiddled with a phrasing nit. This approval is not about the diagram picture, but the content of md that substitutes Identity Documents with Credentials.

2024-07-21 23:11 UTC, merged