Update arch digram to match terminology
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #311
Opened 2024-11-03 11:34 UTC by thibmeu

Update Figure 1 to include components from the Terminology.

* Credentials is owned by an Issuer
* Collection of receipt is done by a Relying Party
* Make of Transparency Statement is done by an Auditor, which is a special Relying Party

The newly generated diagram looks as follow
![a](https://github.com/user-attachments/assets/f94f7b31-678a-4f0b-96d2-a6f77705103b)

2024-11-03 13:25 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +              V                           |   |
```suggestion
              |                           |   |
              V                           |   |
```

2024-11-03 15:38 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> + | Statement |      +---------+--+---------+
```suggestion
       v             +--------------------+
  .----+----.        | Issuer Credentials |
 | Statement |       +--------+--+--------+
```

2024-11-03 15:40 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +              |             +---------+   |
```suggestion
              | '----------+---------+    |
              |            | Auditor |    |
              |            +---------+    |
```

2024-11-03 15:40 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +        +---------------+        +---------------+
```suggestion
  .-----------+----------.    .-----------+------.
 /  Collecting Receipt  /    /    Replay Log    /
'------+---------------+    '--+---------------+
       | Relying Party |       | Relying Party |
       +---------------+       +---------------+
```

2024-11-03 15:42 UTC, SteveLasker approved these changes
Thanks, @thibmeu 
LGTM

Minor tweaks to fix the aasvg corners:
![image](https://github.com/user-attachments/assets/3252563d-78e3-4d32-bb94-90c39699db23)

2024-11-03 16:04 UTC, aj-stein approved these changes

2024-11-04 08:49 UTC, JAG-UK approved these changes
Lgtm

2024-11-04 09:29 UTC, yogeshbdeshpande commented
@thibmeu I have a slight concern with the diagram. Normally Replay log is explicitly done by Auditor so Under Replay Log, if the role is Auditor that is a more correct representation than a Generic Relying Party what you have currently!

2024-11-04 09:33 UTC, yogeshbdeshpande commented
Also I have a concern, Verify Transparent Statements is a job of any Relying Party, not specifically for the Auditor?

Did you intend to attach, the Auditor role to Verify Transparent Statements?

2024-11-04 09:35 UTC, yogeshbdeshpande requested changes
Kindly answer these questions please before I can approve, happy to discuss face to face!

2024-11-04 09:42 UTC, thibmeu commented
> Also I have a concern, Verify Transparent Statements is a job of any Relying Party, not specifically for the Auditor?

From the terminology
```
Auditor: checks the correctness and consistency of all Transparent Statements issued by a Transparency Service
Relying Party: consumes Transparent Statements, verifying their proofs and inspecting the Statement payload
```

I read this as the Auditor builds verified transparent statement, while the replay log is a specialised relying Party but not necessarily an auditor

Removing Auditor is also a possibility to not put too many entities, since it's relying parties anyway. What do you think?

2024-11-04 11:42 UTC, thibmeu commented
@yogeshbdeshpande I've addressed your comments following a discusion we had in person
here is the updated diagram

![Screenshot from 2024-11-04 11-41-47](https://github.com/user-attachments/assets/ca0837ae-7b15-48da-9e56-9aea72e07078)

2024-11-04 13:06 UTC, yogeshbdeshpande approved these changes
Thank you for making this important change!
Looks Good to Me

2024-11-07 10:34 UTC, merged