Add use case from original use case document
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #328
Opened 2024-12-20 18:27 UTC by rjb4standards

Added one use case from original use case document: Signing certificate authenticity use case

2024-12-31 04:28 UTC, aj-stein commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
What does authorized mean in the context of all possible subjects of a statement by an issuer? For freely and openly licensed software, there are little or no restrictions on a producer of software, not to speak of public domain work.

Is there alternative wording for authorized? I have thought of it for a little while, but have yet to find alternative wording I could propose. I will think about it some more though.

2024-12-31 04:29 UTC, aj-stein commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
Like my previous comment, are there more neutral and perhaps less loaded terms than illegitimate?

2024-12-31 04:31 UTC, aj-stein reviewed
I added some comments because it seems we are adding subjective descriptions that do not make the draft more crisp and clear. Can we consider alternatives?

2024-12-31 13:38 UTC, rjb4standards commented
AJ, I'm open to other terminology that will emphasize the need to confirm a trusted party as producer and signer of digital objects. Perhaps the term legitimate could replace authorized.

2025-01-03 15:43 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
SCITT doesn't support embedded signatures, as they don't support the multi-party/post-build processes.
```suggestion
The released software component is accompanied by a statement of authenticity (e.g., a detached signature).
```

2025-01-03 15:44 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +Some providers include this particular software component as part of their release product package bundle and provide the product package with proof of authenticity using their own issuer authority.
```suggestion
Some providers include this particular software component as part of their release product/package bundle and provide the package with proof of authenticity using their issuer authority.
```

2025-01-03 15:48 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
@SteveLasker  you suggest removing embedded signatures. Does this mean that embedded signatures on artifacts are not supported in SCITT?

2025-01-03 15:58 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
I struggle with Authorized as well, as it's also not clear who is stating who should be "authorized" and to whom?

A consuming company may authorize EntityA, but not EntityB, while another may require a different Entity to produce the same package, such as RedHat or a specific Industry "authorized" endorsement.

Originating could also be questioned. 
At the end of the day, the verifier makes a decision which issuers they trust, for a given environment.

2025-01-03 16:06 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
@SteveLasker would it help to replace "authorized" with "legitimate".

People need to be able to determine if an artifact is to be trusted, or not, based on a verifiable method. I'm asserting that the presence of an artifact in a SCITT registry is sufficient to make it trustworthy, but the process used to register an artifact in a SCITT trust registry needs to be able to discern a trustworthy artifact and one that is false, or not trustworthy.

Somehow, the SCITT "solution" needs to be able to discern trusted artifacts from untrusted artifacts and the ability to establish trust in the artifacts supply chain is key to this process. Only trusted artifacts, submitted by trusted parties make their way into a SCITT trust registry, IMO.

2025-01-03 17:02 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
I'm suggesting we remove references to embedded signatures as SCITT doesn't know about them.
The content also conflates a few different concepts of attached/detached payloads, referencing an artifact the statement is about, and attached signatures that are not part of the SCITT Architecture. 

I'm going to suggest the following change.

SCITT doesn't support embedded signatures, as they don't support the multi-party/post-build processes.
```suggestion
The released software component is accompanied by a statement of authenticity.
```

2025-01-03 17:05 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
How does an entity determine trust?

2025-01-03 17:08 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
@SteveLasker Many post build artifacts, like MSI installation packages contain embedded digital signatures. This change seems to allow either/or embedded/detached authenticity evidence.

2025-01-03 17:11 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
@SteveLasker I'm hoping the SCITT spec will describe how trust is ascertained before an item is placed into the registry. Then parties can simply trust an artifact because it is in the registry, and has been properly vetted as trustworthy. This is how a "Registry of Deeds" works, which IMO is a good model for a SCITT Trust Registry. Only trusted artifacts can be placed into the registry.

2025-01-14 08:45 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +Some providers include this particular software component as part of their release product package bundle and provide the product package with proof of authenticity using their own issuer authority.
harmless, editorial

2025-01-14 08:46 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
Let's make this (item 1) in a corresponding consensus-building discussion.

2025-01-14 08:46 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
Let's make this (item 2) in a corresponding consensus-building discussion.

2025-01-14 08:47 UTC, henkbirkholz commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
part of (item 2)

2025-01-14 13:03 UTC, aj-stein commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
> Let's make this (item 2) in a corresponding consensus-building discussion.

What's the venue or media for that discussion, the mailing list?

2025-01-14 13:10 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
Good idea, Henk. No objection.
The SCITT protocol must exhibit a process is indeed designed to ensure trust, as best as possible. We should try to remove as much uncertainty as possible from the protocol so that people will know a SCITT registry is genuinely a source of trustworthy materials

2025-01-14 13:17 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +A software component (e.g., a library or software product) released by a certain original producer is common practice for both open-source and commercial offerings.
```suggestion
A software component (e.g., a library or software product) released by a legitimate producer is common practice for both open-source and commercial offerings.
```

2025-01-14 13:18 UTC, yogeshbdeshpande reviewed
Lets discuss more about the change, as suggested by Henk!

2025-01-15 15:03 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +A software component (e.g., a library or software product) released by a certain original producer is common practice for both open-source and commercial offerings.
I'm fine with this change, in the context of this use case.

2025-01-15 15:14 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +A software component (e.g., a library or software product) released by a certain original producer is common practice for both open-source and commercial offerings.
I support these enhancements.

2025-01-16 13:57 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
I like the @SteveLasker suggestion of terminating sentence at authenticity.

2025-01-16 13:58 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
```suggestion
* understand if a particular provider is actually a legitimate producer or an alternative party
```

2025-01-16 13:59 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
```suggestion
* reliably discern if a provider is the original, legitimate producer or is a trustworthy alternative provider or is an illegitimate provider
```

2025-01-16 13:59 UTC, yogeshbdeshpande reviewed
@henkbirkholz I made few more suggestions inline with what you just commited, to make the PR more compelete. Please have a look and take the changes, if you agree!

2025-01-16 14:04 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
I can support this enhancement on line 320.

2025-01-16 19:40 UTC, JAG-UK commented on draft-ietf-scitt-architecture.md
> +The released software component is accompanied by a statement of authenticity (e.g., an embedded or a detached signature).
I also like the approach of terminating the sentence early. Cut early, cut often!

More seriously, it's an (eg) so...

2025-01-16 19:40 UTC, JAG-UK commented on draft-ietf-scitt-architecture.md
> +* understand if a particular provider is actually the original authorized producer or an alternative party
It's probably fair to take that to the mailing list since it will read into what non-SCITT WGs might want to do with SCITT. Making sure we have the meaning of an Issuer signature really understood is no bad thing

2025-01-20 17:20 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
Does using "legitimate" require the definition of what makes an issuer "legitimate"? 
"Trusted" is the choice of the verifier, or the TS when notarizing the signed statements. This seems more well-understood and less controversial.

2025-01-20 17:26 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
No objection to this enhancement.

2025-01-21 15:56 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +A software component (e.g., a library or software product) released by a legitimate producer is common practice for both open-source and commercial offerings.
```suggestion
A software component (e.g., a library or software product) released by a trusted producer is common practice for both open-source and commercial offerings.
```

2025-01-21 15:59 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
Based on the call 1/21/25, we've settled on "trusted" for line 301 and 320. 
Please reactivate if you feel strongly

2025-01-21 16:03 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
No objections to this consensus position. Good compromise. I presume that someone will make this change and I don't have to make this change - correct?

2025-01-21 19:19 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +* reliably discern if a provider is the original, trusted producer or is a trustworthy alternative provider or is an illegitimate provider
Hi, @rjb4standards, yes the changes were committed to this PR. Please review: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/328/files

2025-01-21 19:21 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +      Dick contributed some software supply chain use cases consistent with US DHS CISA Secure by Design principles and practices
Reducing the text a bit to focus on the IETF doc content.
```suggestion
      Dick contributed to the software supply chain use cases.
```

2025-01-21 19:23 UTC, SteveLasker requested changes
This is making good progress. I'd like to recognize the other [authors of the use-cases doc](https://datatracker.ietf.org/doc/draft-ietf-scitt-software-use-cases/) before merging this PR, however I need to confirm with them prior to merging.

2025-01-21 19:28 UTC, rjb4standards reviewed
Perfect, thanks @SteveLasker  and @henkbirkholz  for your help in resolving this matter.

2025-01-21 19:49 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +      Dick contributed some software supply chain use cases consistent with US DHS CISA Secure by Design principles and practices
No objection Steve.

2025-01-21 19:52 UTC, knight-brian requested changes
@SteveLasker: Thank you for your note on use case recognition.  The data requested are below.

- ins: B. Knight
  name: Brian Knight
  org: Microsoft
  email: brianknight@microsoft.com
  country: United States

2025-01-21 20:19 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +
```suggestion

ins: B. Knight
name: Brian Knight
org: Microsoft
email: [brianknight@microsoft.com](mailto:brianknight@microsoft.com)
country: United States
```

2025-01-21 20:20 UTC, rjb4standards commented on draft-ietf-scitt-architecture.md
> +
No objection

2025-01-21 20:22 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
```suggestion
```

2025-01-22 18:47 UTC, SteveLasker approved these changes
Additional Use Case contributors are now added. LGTM

2025-01-22 18:57 UTC, rjb4standards commented
LGTM @SteveLasker 
Thanks for leading us through this update.

2025-01-28 19:40 UTC, knight-brian approved these changes
Changes approved.  Thanks!

2025-01-29 08:07 UTC, henkbirkholz approved these changes

2025-01-29 09:22 UTC, JAG-UK approved these changes
One minor nit but it's fine.

2025-01-29 09:22 UTC, JAG-UK commented on draft-ietf-scitt-architecture.md
> +A software component (e.g., a library or software product) released by a trusted producer is common practice for both open-source and commercial offerings.
I had to read this about 5 times before I could convince myself it makes grammatical sense, but I'm OK with it now. Won't risk resetting all the other ticks to request a clarification.

2025-01-29 10:51 UTC, yogeshbdeshpande approved these changes
LGTM!

2025-01-29 15:22 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +A software component (e.g., a library or software product) released by a trusted producer is common practice for both open-source and commercial offerings.
nod. If we can come up with a suggestion, we can merge in an editorial update.

2025-01-29 15:23 UTC, merged

2025-01-29 15:35 UTC, rjb4standards commented
One minor suggestion:

A software component (e.g., a library or software product) released by a trusted producer is an **essential practic**e for both open-source and commercial offerings.

2025-01-29 15:36 UTC, rjb4standards commented
replaced common with "essential"