Change receipts 394 to a TBD with IANA Considerations
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #332
Opened 2024-12-23 23:17 UTC by SteveLasker

Fixes #326

2025-01-14 13:01 UTC, aj-stein commented on draft-ietf-scitt-architecture.md
> +
If the authors of that spec are requesting it for that draft, why are we doubling that request here? Do we not need to specify we want to replace the values later once that is formalized with an explanation between this section and the previous header?

2025-01-20 17:26 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +
It's a little repetitive. We must change 394, as it creates confusion for implementors. This section was copy/pasted over for completeness. Either way, when TBD_0 is assigned, this will get cleaned up, so I felt it was helpful to provide a pointer.

2025-01-22 18:51 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +
@aj-stein, do still feel strongly? I'd like to merge to get to #341

2025-02-11 15:26 UTC, JAG-UK approved these changes
LGTM, although we should go and try to get allocation ASAP

2025-02-11 15:37 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +## COSE Receipts Header Parameter
Normally you would request IANA with definitive number ranges for your work!

Please check with @henkbirkholz how best we can handle this ?

Adding IANA Considerations is a great start!

2025-02-11 15:37 UTC, yogeshbdeshpande reviewed
See my suggestions!

2025-02-11 15:40 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +
This is weird... you are duplicating the registration request from an existing draft:

https://datatracker.ietf.org/doc/html/draft-ietf-cose-merkle-tree-proofs-07#name-new-entries-to-the-cose-hea

2025-02-11 15:41 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +- Description: Priority ordered list of CBOR encoded Receipts.
TBD_0 is requested in {{-COMETRE}}.

2025-02-11 15:42 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +- Description: Priority ordered list of CBOR encoded Receipts.
```suggestion
TBD_0 is requested in {{-COMETRE}}.
```

2025-02-11 15:51 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +- Description: Priority ordered list of CBOR encoded Receipts.
Good catch @OR13 : I think, then we do not need this PR??

2025-02-11 15:52 UTC, yogeshbdeshpande requested changes
If this is the ONLY tag, then we can drop this PR, as suggested by @OR13

2025-02-17 15:15 UTC, SteveLasker commented on draft-ietf-scitt-architecture.md
> +## COSE Receipts Header Parameter
This PR is to avoid readers implementing numbers that are not assigned.
While we're pursuing assignment, we should merge this PR to indicate the numbers are not yet assigned.

2025-02-17 15:53 UTC, OR13 approved these changes

2025-02-18 15:08 UTC, merged