Include COSE HASH Envelope reference
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #334
Opened 2024-12-23 23:28 UTC by SteveLasker

Fixes #333

2024-12-31 04:38 UTC, aj-stein commented on draft-ietf-scitt-architecture.md
Should nay not be MAY per BCP14 or was it an intentional choice to cap it lowercase?

2024-12-31 04:39 UTC, aj-stein reviewed
Some preliminary questions on keywords

2025-01-16 22:56 UTC, OR13 requested changes
This is just tangling drafts together for no real benefit.

A signed statement is a cose sign1, we don't need to say more than that.

2025-01-20 17:32 UTC, SteveLasker commented
Do we want to cover in SCRAPI: https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/issues/43
f

2025-02-17 15:11 UTC, closed without merging