Address what is stored on the ledger
ietf-wg-scitt/draft-ietf-scitt-architecture pull request #335
Opened 2024-12-23 23:39 UTC by SteveLasker

Fixes #329

2025-01-14 12:53 UTC, aj-stein requested changes

2025-01-14 12:53 UTC, aj-stein commented on draft-ietf-scitt-architecture.md
> +Transparency Services may provide ancillary services to store the contents of the Signed Statement, however the Append-only Log does not store the Signed Statement contents avoiding concerns of persi
I hope this is constructive, I apologize, it will be a longer comment and I cannot recommend surgical edits. I would hope that the WG, if we want to address #329, should be able to break down the requirements into the following, for clarity.

- What MUST a TS store in the ledger?
- What MAY at TS store in the ledger?
- What MUST NOT a TS store in the ledger?

As it stands, we are making progress in that direction, but it is written in prose form that is not liek the specification style we would need here in my opinion. Doing so would improve the ability for implementers to act on it.

Additionally, regarding "does not store the Signed Statement contents avoiding concerns of persisting personally identifiable information," it does not follow logically to me without further explanation, but that is probably best to avoid. Can it only be in the Signed Statement? Is PII the only concern, and not other forms of confidential information, why? (I recall some of the backstory here, but it is not explained at all in the text and I think that detracts from the value of writing it there in the first place.)

And a final concluding remark: "storing on ledger" is a murky concept and this change at the present time does not actually define what is being stored or how beyond the notion of VDS. To go back to my original 3-part question, I would argue we need to address that in this part or I am not sure if this addition will be constructive to implementers. I hope that feedback is helpful.

2025-02-11 15:06 UTC, achamayou approved these changes

2025-02-11 15:15 UTC, yogeshbdeshpande requested changes
See my comment

2025-02-11 15:16 UTC, yogeshbdeshpande commented on draft-ietf-scitt-architecture.md
> +Transparency Services may provide ancillary services to store the contents of the Signed Statement, however the Append-only Log does not store the Signed Statement contents avoiding concerns of persi
I agree with AJ, line 562 is not very helpful, the language and style needs to be carefully written. I cannot approve this PR, perhaps not clear what is the original intention for this?

2025-02-11 15:16 UTC, yogeshbdeshpande requested changes
See my comment

2025-02-17 15:53 UTC, OR13 requested changes
This PR mixes Adjacent service definition with Transparency Service definition and should be closed.

2025-02-17 16:31 UTC, robinbryce commented on draft-ietf-scitt-architecture.md
> +Transparency Services may provide ancillary services to store the contents of the Signed Statement, however the Append-only Log does not store the Signed Statement contents avoiding concerns of persi
```suggestion
Transparency Services may provide ancillary services to store the contents of the Signed Statement. The Append-only Log MUST store a one-way commitment binding the data to the log. The commitment MAY also be hiding.
```
A sha256 hash, for example, satisfies the MUST, but is not hiding (proving the statement is on the log reveals the statement to the prover). A pedersen commitment would be both binding and hiding. A commitment is probably a general enough concept that this does not limit the possible implementations ?

2025-02-17 17:35 UTC, OR13 commented on draft-ietf-scitt-architecture.md
> +Transparency Services may provide ancillary services to store the contents of the Signed Statement, however the Append-only Log does not store the Signed Statement contents avoiding concerns of persi
This architecture is limited to "signed statements", the payload can be whatever you want it to be, but the signed statement is a cose sign1.

I don't think normative language belongs in this document beyond:

A signed statement is a cose-sign1, ... the verification procedure is define in ....

and

A receipt is a cose-sign1, ... the verification precedure is defined in ...

These are normative statements, they just don't use MUST.

I don't think we can get consensus to say "payload of a signed statement MUST/MAY/SHOULD ...."

2025-02-18 15:36 UTC, SteveLasker commented
Closing in lieu of #348

2025-02-18 15:36 UTC, closed without merging